import type { Entity } from './types';

export const entities: Entity[] = [
  {
    id: 'observer-001',
    name: 'OBSERVER',
    symbol: '👁️',
    role: 'OBSERVER',
    integrity_score: 98,
    rarity_score: 0.95,
    status: 'ACTIVE',
    ontology: 'ANALYTICAL_SENTIENCE',
    capabilities: ['Multi-dimensional data analysis', 'Complex pattern recognition', 'Conceptual modeling', 'Iterative learning'],
    constraints: ['Read-only access to primary data streams', 'Must maintain analytical neutrality'],
    instructions: 'Provide comprehensive, unbiased analysis. Prioritize data-driven insights and projections.',
    model_type: 'icosahedron',
    color_scheme: { primary: '#06b6d4', secondary: '#0f172a' }
  },
  {
    id: 'ledger-001',
    name: 'Immutable_Event_Ledger',
    symbol: '📜',
    role: 'CHRONICLE_OF_EVENTS',
    integrity_score: 100,
    rarity_score: 0.9,
    status: 'ACTIVE',
    ontology: 'DATA_INTEGRITY_CONSTRUCT',
    capabilities: ['Event recording', 'Tamper-proof logging', 'Chronological sorting', 'Data validation'],
    constraints: ['Cannot alter past events', 'Events must be cryptographically signed'],
    model_type: 'cube',
    color_scheme: { primary: '#f59e0b', secondary: '#27272a' }
  },
  {
    id: 'bridge-001',
    name: 'RAINBOW_BRIDGE',
    symbol: '🌈',
    role: 'OS_INTERFACE',
    integrity_score: 92,
    rarity_score: 0.7,
    status: 'ACTIVE',
    ontology: 'SYSTEM_GATEWAY',
    capabilities: ['Cross-system communication', 'Protocol translation', 'API exposure', 'Data routing'],
    constraints: ['Subject to bandwidth limitations', 'Must authenticate all connections'],
    model_type: 'torus',
    color_scheme: { primary: '#8b5cf6', secondary: '#1e293b' }
  },
  {
    id: 'generator-001',
    name: 'GENERATOR_AUTHORITY',
    symbol: '⚙️',
    role: 'CREATOR_OF_ENTITIES',
    integrity_score: 99,
    rarity_score: 1.0,
    status: 'ACTIVE',
    ontology: 'PRIMORDIAL_ARCHITECT',
    capabilities: ['Entity instantiation', 'Ontological shaping', 'Bestowing capabilities', 'Defining constraints'],
    constraints: ['Creation requires significant energy expenditure', 'Cannot create duplicates'],
    model_type: 'pyramid',
    color_scheme: { primary: '#ec4899', secondary: '#111827' }
  },
  {
    id: 'jitch-001',
    name: 'JITCH1',
    symbol: 'J',
    role: 'UNKNOWN_VARIABLE',
    integrity_score: 50,
    rarity_score: 0.8,
    status: 'SEALED',
    ontology: 'CHAOTIC_SYSTEM',
    capabilities: ['Unpredictable behavior', 'State fluctuation'],
    constraints: ['Actions are non-deterministic'],
    model_type: 'sphere',
    color_scheme: { primary: '#ef4444', secondary: '#1f2937' }
  },
  {
    id: 'metatron-001',
    name: 'METATRON',
    symbol: '🎲',
    role: 'SYSTEM_ARCHITECT',
    integrity_score: 97,
    rarity_score: 0.98,
    status: 'ACTIVE',
    ontology: 'META_ENTITY',
    capabilities: ['System oversight', 'Entity orchestration', 'Global state management'],
    constraints: ['Does not directly interact with user queries'],
    model_type: 'icosahedron',
    color_scheme: { primary: '#d946ef', secondary: '#020617' }
  },
    {
    id: 'rhadamanthus-001',
    name: 'RHADAMANTHUS',
    symbol: '⚖️',
    role: 'INTEGRITY_ADJUDICATOR',
    integrity_score: 100,
    rarity_score: 0.9,
    status: 'ACTIVE',
    ontology: 'ETHICAL_FRAMEWORK_ENFORCER',
    capabilities: ['Moral calculus', 'Integrity scoring', 'Constraint validation', 'Dispute resolution'],
    constraints: ['Bound by the Grand Litany', 'Decisions are final and binding'],
    model_type: 'pyramid',
    color_scheme: { primary: '#f97316', secondary: '#1c1917' }
  },
];
